import os

PERSONALITY_INSIGHTS_USERNAME = os.getenv('PERSONALITY_INSIGHTS_USERNAME', default='')
PERSONALITY_INSIGHTS_PASSWORD = os.getenv('PERSONALITY_INSIGHTS_PASSWORD', default='')
TWITTER_API_USERNAME = os.getenv('TWITTER_API_USERNAME', default='')
TWITTER_API_PASSWORD = os.getenv('TWITTER_API_PASSWORD', default='')
